Add search and zip features
devclub-iitd/Citadel pull request #18
Opened 2018-05-29 11:45 UTC by kabirtomer

This is to add the implementation of 
- Change in the database. All approved files are now stored in media/files, with a .meta file in their place containing within the title the filename and a link to the actual file, and storing the file's meta tags for search purposes.
- Interactive Search to the frontpage. 
- Filename Search to the approvals page.
- Finalize Approvals link that zips and stores courses.

2018-05-29 11:49 UTC, ankurshaswat commented
Create a script to make the required folders.
Commenting is not standaradized. 3 types of commenting used // , ''' (Single line) , ''' (Multiline)

2018-05-29 13:38 UTC, aman71197 commented
The code is broken. 
Cloning `kabir:master` and running `python manage.py runserver` gives an import error.
` File "/tmp/BookShelf/bookShelf/books/urls.py", line 3, in <module>
    from . import views
  File "/tmp/BookShelf/bookShelf/books/views.py", line 22, in <module>
    from books import search as search
  File "/tmp/BookShelf/bookShelf/books/search.py", line 1, in <module>
    from . import views
ImportError: cannot import name 'views'`

2018-05-29 13:49 UTC, aagrxyz requested changes
Function APIsearch is repeated in views.py 
Check lines 265 to 300

2018-05-29 14:20 UTC, aman71197 commented
There are multiple places where file paths have been joined manually with just string concatenation.
Change all of them to os.path.join
This is necessary to make it platform independent and for an error-free code

2018-05-29 14:22 UTC, aagrxyz requested changes
There are multiple places where file paths have been joined manually with just string concatenation.
Change all of them to os.path.join
This is necessary to make it platform independent and for an error-free code

2018-05-30 08:36 UTC, aagrxyz approved these changes

2018-05-30 08:40 UTC, aagrxyz requested changes
course_downloads.txt is not created automatically the first time. Make sure you create the file in the necessary format if it is not present.

[Err] No such file or directory: 'course_downloads.txt'
Request Method: | GET
http://localhost:8000/books/download_course/?course=COL106

2018-05-31 06:15 UTC, aagrxyz approved these changes

2018-05-31 06:22 UTC, aagrxyz commented
Presently the media/files directory just contains the dump of files. So now let's say multiple courses have a file known as lec1.pdf then the files will be overwritten.  I added two different files, but both named as lec01.pdf to COL202/Professors/amitk/ and COL352/Professors/naveen/
Finally, after Finalize Approvals, both the lec01.pdf in COL202 and COL352 pointed to the file lec01.pdf in the COL352 directory.
This seriously limits the names, that we can give to files. This should not be the case.

2018-05-31 06:23 UTC, aagrxyz requested changes
Overwriting of files with same name,

2018-06-01 02:16 UTC, aman71197 commented
When the admin, clicks to view a file the browser treats it as a Binary file, as it doesn't have an extension.
Like MT$MTL100$Professors$atripath$Notes$[Spring18]-MTL100-Notes-random.pdf==MTL100$atripath
If you click, to see its content, it is treated as a binary file.

2018-06-01 02:41 UTC, aagrxyz requested changes

2018-06-01 02:41 UTC, aman71197 commented on bookShelf/books/views.py
> +	return redirect('/../media/database/' + parent_dir + '/' + course + '.zip')
Use the declared global variables to get the file. Don't Hardcode

2018-06-01 02:41 UTC, aman71197 commented on bookShelf/books/views.py
> +				file_path=temp_path
File path doesn't have an extension, causing it to act as a binary file.

2018-06-01 02:41 UTC, aman71197 commented on bookShelf/books/views.py
> +								zf.write(file_loc, arcname=to_write)
This causes file not found error, when clicking on finalize approvals, in a course that just got its first file.

2018-06-01 02:59 UTC, aagrxyz requested changes
There is still conflict between two files having the same name when they are pasted manually. We need to work a better way to store the meta data. Having just a single dump of files has a lot of problems.

2018-06-08 05:58 UTC, aagrxyz requested changes

2018-06-08 05:58 UTC, aman71197 commented on bookShelf/books/views.py
>  	try:
Do this in 2 separate try catch blocks. It is possible that first one causes error and so .meta file will bot be deleted

2018-06-08 06:08 UTC, aman71197 commented
Change The structure of task_file.json
Presently you need to iterate over all courses once in removal and once in additions
Instead store the structure as


`[
    { course: "COLxxx" , change:" something" , type: "addition" , timestamp: "xxxxx"} ,
   { course: "COLxxx" , change:" something" , type: "removal" , timestamp: "xxxxx"}
]`
Thus store each addition and removal as a list of actions that need to be performed on it with the timestamp. This is necessary as there is an order in the actions performed by the user and we don't want to have an arbitrary order on the actions.

2018-06-11 08:40 UTC, aman71197 commented
Rename button at Admin panel is not working
Got the following error: 
NameError at /books/rename/
name 'name' is not defined

2018-06-11 09:09 UTC, aagrxyz requested changes

2018-06-11 09:09 UTC, aagrxyz commented on bookShelf/books/views.py
>  	try:
@kabirtomer Look into this

2018-06-11 09:09 UTC, aman71197 commented on bookShelf/books/views.py
> +		task[TIMESTAMP] = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
Add timezone to this. Make sure this timestamp is  in GMT+5:30

2018-06-11 09:17 UTC, aman71197 commented
1. Upload Form Does not have an option to fill in meta data tags
2. Whenever the user downloads the file, the file is saved with name as "download". Need to send some header that states the name of file to be stored when downloaded.
3. Remove empty folders from bulk directory after you have moved files to the database directory

2018-06-12 09:49 UTC, aman71197 commented
I have made some changes in the code. The code related to search feature is still left to be reviewed.
@mayanksingh2298 Go through all the code once and update your progress here.
Also @kabirtomer , a lot of work needs to be done at the UI side. Make sure that is done.

2018-06-14 19:04 UTC, mayanksingh2298 commented
![image](https://user-images.githubusercontent.com/25145295/41432481-e704b896-7033-11e8-9b4c-927da29c8dfd.png)
The highlighted line is not required

2018-06-14 19:13 UTC, mayanksingh2298 commented
![image](https://user-images.githubusercontent.com/25145295/41432917-09e869c4-7035-11e8-961b-b4d0ebe66055.png)
remove  "(Create a super user by following the instructions)"
The second last line gives an error:
![image](https://user-images.githubusercontent.com/25145295/41432953-2383e480-7035-11e8-825c-cf865d3081ef.png)

2018-06-15 07:56 UTC, aman71197 commented
![image](https://user-images.githubusercontent.com/18374988/41456513-a8882f7a-70bb-11e8-9712-081f56045b54.png)
1. Why is there so much white space on the left,right and bottom margin. Make use of every space on the screen and increase the size of the div.
2. To search a file, I need to manually click on the search button. Add an event listener for enter key in that form.
3. Clicking on reset buttons does not clear the search box.

![image](https://user-images.githubusercontent.com/18374988/41456649-18cfd526-70bc-11e8-88c9-f5a329194a93.png)

4. Make the "NEXT" button blue in color (by default, not only on hovering the mouse) to match our color scheme and put it in the center of the div, and reduce it's width.

And good work on that tag form, it looks amazing.

2018-06-15 07:58 UTC, aagrxyz approved these changes

2018-06-16 13:53 UTC, merged